# Generated by Django 4.1.3 on 2022-11-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_todo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='title',
        ),
    ]
